/*
Author: Damian Archer
Course: CIS 215
Date: 6-25-2021
Assignment: Week 6 -- Functions.cpp
Comments:
*/

#include <iostream>
#include <cstdlib>
#include <ctime>
#include <cmath>
using namespace std;

// function prototypes
double calcSqRt(unsigned odd);
unsigned calcSquare(unsigned even);
void oddOrEven(unsigned num);
unsigned randomInt();

int main()
{
	int num;
	cout << "Random integer " << (num = randomInt()) << " generated by call to randomInt()" << endl;
	oddOrEven(num);
}

unsigned randomInt()
{
	srand(static_cast<unsigned int>(time(0)));
	return 1 + rand() % 100;
}

void oddOrEven(unsigned num)
{
	if (num % 2 == 0)
		cout << "The square of even integer " << num <<  " returned by call to calcSquare() is " << calcSquare(num) << endl;
	else
		cout << "The square root of odd integer " << num << " returned by call to calcSqRt() is " << calcSqRt(num) << endl;
}

unsigned calcSquare(unsigned even)
{
	return even * even;
}

double calcSqRt(unsigned odd)
{
	return sqrt(odd);
}


